# Generated by Django 4.2.6 on 2023-11-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('premios', models.TextField(blank=True, null=True)),
                ('anio_debut', models.PositiveIntegerField()),
            ],
        ),
    ]
